#! /bin/sh

sxhkd -c ~/.config/sxhkd/sxhkdrc &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d Ⅰ II III IV V

bspc config border_width         1

bspc config window_gap          20

bspc config focused_border_color "#C5C8C6"
bspc config normal_border_color "#141516"




bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


#autostart
killall -q polybar
bash ~/.config/polybar/launch.sh
nitrogen --restore &
picom --experimental-backends -b

