#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 II III IV V 6 7 8   

bspc config border_width         4
bspc config window_gap          20


bspc config focused_border_color "#C5C8C6"
bspc config normal_border_color "#141516"

bspc rule -a Oblogout state=fullscreen
bspc rule -a Pcmanfm state=floating
bspc rule -a Anki state=floating
#bspc rule -a '*' state=floating
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false


bspc rule -a MEGAsync desktop='^8' state=floating follow=off
bspc rule -a notion-app desktop='^7' follow=off
bspc rule -a obsidian desktop='^1' follow=off
bspc rule -a Signal desktop='^3' follow=off
#bspc rule -a Pomodoro desktop='^8' follow=off
bspc rule -a barrier desktop='^8'follow=off

#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off



#autostart
killall -q polybar
bash ~/.config/polybar/launch.sh
nitrogen --restore &
picom --experimental-backends -b &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
megasync & 
obsidian &
notion-app &



